### ISSUE TITLE
Experiments from paper

### ISSUE THREAD

**Issue by stanleyjs** [const-ae/transformGamPoi#2]
Hi,

Do you have any of the experiments from your preprint able to be published?

Jay

**Comment by const-ae** [comment]
Hi Jay,

sorry for the delay. I was on holiday for the last two weeks.

> Do you have any of the experiments from your preprint able to be published?

All the data that I used in the paper are available publicly. For a list of sources and how to best access them see page 18.

![image](https://user-images.githubusercontent.com/5359014/128486142-2ea6df6e-3762-42d9-8273-9e0880340761.png)

Best Regards,
Constantin
