### ISSUE TITLE
Overdispersion parameter

### ISSUE THREAD

**Issue by cnk113** [const-ae/transformGamPoi#4]
Hey Constantin,

When using shifted_log_transform, should we just use the overdispersion parameter default .01? Your preprint states that there's no right answer so I was wondering if you have recommended guidelines? If your samples is heterogeneous and uses 10x chemistry would .01 be fine?

Best,
Chang

**Comment by const-ae** [comment]
Hi Chang,

I cannot give a general guideline on what overdispersion to pick, as the correct answer depends on the precise biological question that you want to study. 

Overall, I would recommend to just pick one (e.g., 0.01) and then later try out if different values change the result of your analysis (I guess that it probably doesn't). If you set the overdispersion to 0, 0.01, or 0.1 and find that you get relevantly different results, I recommend worrying about this and would advise investigating further why the overdispersion parameter has a significant impact.

Best,
Constantin
