### ISSUE TITLE
question about the delta method transformation

### ISSUE THREAD

**Issue by skwalker** [const-ae/transformGamPoi#6]
Hi, I'm wondering about the math in `delta_method_transform.R`:

```
.log_plus_alpha_impl <- function(x, alpha){
  1/sqrt(alpha) * log1p(4 * alpha * x)
}
```
From the paper, I thought the delta transform was supposed to be `log(x + 1/(4 * alpha))`, where x is the library size-transformed count?

If so, shouldn't this function be returning `log1p(4 * alpha * x)-log(4 * alpha)`? This would lose sparsity, which doesn't seem right to me...

Thanks,
Sarah

**Comment by const-ae** [comment]
Hi Sarah,

sorry for the late reply. In terms of variance-stabilization it doesn't matter if you add or subtract a constant. From this perspective `log1p(4 * alpha * x)-log(4 * alpha)` and `log1p(4 * alpha * x)` are equivalent.

Best,
Constantin
